[default]
description = "Default permissions for the stem-recorder plugin"
permissions = [
  "allow-list-devices",
  "allow-start-monitor",
  "allow-stop-monitor",
  "allow-start-record",
  "allow-stop-record",
  "allow-get-stats",
  "allow-verify-wav",
]
